"""Full PRNG sequence analysis from 64KB capture"""
import sys, subprocess, re
sys.stdout.reconfigure(line_buffering=True)

TSHARK = r"C:\Program Files\Wireshark\tshark.exe"
CAP = r"C:\dev\winols-roadrunner-bridge\tools\rr_prng_full.pcapng"
CAP_ADDR = r"C:\dev\winols-roadrunner-bridge\tools\rr_addr_test.pcapng"

def extract_keys(cap_file):
    result = subprocess.run([TSHARK, "-r", cap_file, "-T", "pdml"],
                           capture_output=True, text=True, errors='replace')
    output = result.stdout + result.stderr
    blocks = []
    for m in re.finditer(r'if_a_tx_payload.*?value="([0-9a-f]{528})"', output, re.DOTALL):
        data = bytes.fromhex(m.group(1))
        if data[0] == 0x57:
            blocks.append({'token': data[2:4].hex(), 'extra': data[4:7].hex(),
                           'key': data[7:263]})
    return blocks

addr_blocks = extract_keys(CAP_ADDR)
BASE_KEY = bytes(addr_blocks[0]['key'])

def find_shift(base, target):
    b = bytes(target)
    f = b[0]
    for s in range(256):
        if base[s] == f:
            if all(b[i] == base[(i+s)%256] for i in range(256)):
                return s
    return None

full_blocks = extract_keys(CAP)
print(f"64KB capture: {len(full_blocks)} blocks")

shifts = []
for b in full_blocks:
    s = find_shift(BASE_KEY, bytes(b['key']))
    shifts.append(s)

print(f"Shifts ({len(shifts)} values):")
for i in range(0, len(shifts), 16):
    row = shifts[i:i+16]
    print(f"  [{i:3d}]: {' '.join(f'{s:3d}' for s in row)}")

# Check if this is a 256-permutation PRNG based on BASE_KEY
print("\n=== Test: shift[n+1] = BASE_KEY[shift[n]] ? ===")
base_lookup_ok = all(BASE_KEY[shifts[i]] == shifts[i+1] for i in range(len(shifts)-1) if shifts[i] is not None and shifts[i+1] is not None)
print(f"  Base-key lookup rule: {'✓' if base_lookup_ok else '✗'}")
if not base_lookup_ok:
    for i in range(min(10, len(shifts)-1)):
        if shifts[i] is not None and shifts[i+1] is not None:
            expected = BASE_KEY[shifts[i]]
            match = "✓" if expected == shifts[i+1] else "✗"
            print(f"  {match} base_key[{shifts[i]}]={expected} vs shifts[{i+1}]={shifts[i+1]}")

# Find period
print("\n=== Periode der PRNG-Sequenz ===")
for period in range(1, 512):
    if len(shifts) > period:
        if all(shifts[i] == shifts[i % period] for i in range(period, len(shifts)) if shifts[i] is not None):
            print(f"  PERIODE GEFUNDEN: {period}")
            break
else:
    print(f"  Keine Periode <= {len(shifts)//2} gefunden")

# Try to find formula: shift[n+1] = f(shift[n], n)?
print("\n=== LCG Suche (alle Blöcke) ===")
found_lcg = False
for a in range(1, 256, 2):
    for b in range(0, 256):
        ok = True
        for i in range(1, min(20, len(shifts))):
            if (a * shifts[i-1] + b) % 256 != shifts[i]:
                ok = False
                break
        if ok:
            # Verify on more
            if all((a * shifts[i-1] + b) % 256 == shifts[i] for i in range(1, len(shifts))):
                print(f"  GEFUNDEN: a={a}, b={b} → shift[n+1] = ({a}*shift[n]+{b})%256")
                found_lcg = True
                break
    if found_lcg:
        break
if not found_lcg:
    print("  Kein LCG gefunden")

# Save full shift sequence
print(f"\n=== Vollständige Shift-Tabelle (erste 512) ===")
with open(r"C:\dev\winols-roadrunner-bridge\tools\rr_shifts_table.py", "w") as f:
    f.write("# Roadrunner PRNG shift sequence (from power-on)\n")
    f.write("# Generated by writing 64KB zeros and observing cipher\n")
    f.write(f"RR_SHIFTS = {shifts[:512]}\n")
    f.write(f"\n# Base key (256 bytes, all unique)\n")
    f.write(f"RR_BASE_KEY = bytes.fromhex('{BASE_KEY.hex()}')\n")
print(f"Saved to rr_shifts_table.py")
